networks:
  deploy-dev:
    driver: bridge
services:
#  app:
#    container_name: container-service
#    build:
#      context: .
#      dockerfile: ContainerService/Dockerfile
#    environment:
#      ASPNETCORE_ENVIRONMENT: Production
#      ASPNETCORE_HTTP_PORTS: 8082
#    ports:
#      - "8082:8082"
#    networks:
#      - deploy-dev
#    depends_on:
#      - container-db
  container-db:
    container_name: container-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: container_db
      PGPORT: 5435
    ports:
      - "5435:5435"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
volumes:
  postgres-data:
