networks:
  deploy-dev:
    driver: bridge
services:
#  order-service:
#    container_name: order-service
#    image: order-service
#    build:
#      context: .
#      dockerfile: WebApi/Dockerfile
#    environment:
#      ASPNETCORE_ENVIRONMENT: Production
#      ASPNETCORE_HTTP_PORTS: 8081
#    ports:
#      - "8081:8081"
#    networks:
#      - deploy-dev
#    depends_on:
#      - order-service-db
  order-service-db:
    container_name: order-service-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
      PGPORT: 5434
    ports:
      - "5434:5434"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
volumes:
  postgres-data: