networks:
  deploy-dev:
    driver: bridge
services:
  app:
    container_name: order-service
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    networks:
      - deploy-dev
    depends_on:
      - order-db
  order-db:
    container_name: order-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
volumes:
  postgres-data: